import { defineType, defineField } from "sanity";

export const listing = defineType({
  name: "listing",
  title: "Equipment",
  type: "document",
  fields: [
    defineField({ name: "title", title: "Title", type: "string", validation: (Rule) => Rule.required() }),
    defineField({ name: "slug", title: "Slug", type: "slug", options: { source: "title" }, validation: (Rule) => Rule.required() }),
    defineField({
      name: "published",
      title: "Published (visible on website)",
      type: "boolean",
      initialValue: true,
    }),
    defineField({
      name: "status",
      title: "Status",
      type: "array",
      of: [{ type: "string" }],
      options: {
        list: ["For Sale", "For Hire", "Sold"],
        layout: "grid",
      },
      initialValue: ["For Sale"],
    }),
    defineField({ name: "make", title: "Make / Manufacturer", type: "string" }),
    defineField({ name: "model", title: "Model", type: "string" }),
    defineField({ name: "year", title: "Year", type: "number" }),
    defineField({ name: "hours", title: "Operation Hours", type: "number" }),
    defineField({
      name: "mileage",
      title: "Mileage",
      type: "object",
      fields: [
        defineField({ name: "amount", title: "Amount", type: "number" }),
        defineField({
          name: "unit",
          title: "Unit",
          type: "string",
          options: { list: ["km", "miles"], layout: "radio" },
          initialValue: "km",
        }),
      ],
    }),
    defineField({
      name: "fuelType",
      title: "Fuel Type",
      type: "string",
      options: { list: ["Diesel", "Petrol", "Electric", "Hybrid", "LPG", "Gas"], layout: "radio" },
    }),
    defineField({
      name: "transmission",
      title: "Transmission",
      type: "string",
      options: { list: ["Manual", "Automatic"], layout: "radio" },
    }),
    defineField({ name: "quantity", title: "Quantity Available", type: "string" }),
    defineField({
      name: "condition",
      title: "Condition",
      type: "string",
      options: { list: ["New", "Used – Excellent", "Used – Good", "Used – Fair"], layout: "radio" },
    }),
    defineField({
      name: "salePrice",
      title: "Sale Price",
      type: "object",
      fields: [
        defineField({ name: "amount", title: "Amount", type: "number" }),
        defineField({
          name: "currency",
          title: "Currency",
          type: "string",
          options: { list: [
            { title: "£ GBP", value: "GBP" },
            { title: "€ EUR", value: "EUR" },
            { title: "$ USD", value: "USD" },
            { title: "AED", value: "AED" },
            { title: "SAR", value: "SAR" },
          ], layout: "radio" },
          initialValue: "GBP",
        }),
        defineField({ name: "onApplication", title: "Price on Application", type: "boolean", initialValue: false }),
      ],
    }),
    defineField({
      name: "hirePrice",
      title: "Hire Price",
      type: "object",
      fields: [
        defineField({ name: "amount", title: "Amount", type: "number" }),
        defineField({
          name: "currency",
          title: "Currency",
          type: "string",
          options: { list: [
            { title: "£ GBP", value: "GBP" },
            { title: "€ EUR", value: "EUR" },
            { title: "$ USD", value: "USD" },
            { title: "AED", value: "AED" },
            { title: "SAR", value: "SAR" },
          ], layout: "radio" },
          initialValue: "GBP",
        }),
        defineField({
          name: "period",
          title: "Per",
          type: "string",
          options: { list: ["Day", "Week", "Month", "Year"], layout: "radio" },
          initialValue: "Day",
        }),
        defineField({ name: "onApplication", title: "Price on Application", type: "boolean", initialValue: false }),
      ],
    }),
    defineField({ name: "description", title: "Description", type: "text", rows: 5 }),
    defineField({
      name: "metaDescription",
      title: "SEO Meta Description",
      type: "text",
      rows: 2,
      description: "Shown in Google search results. 150–160 characters recommended. Leave blank to auto-generate from title, make, model and category.",
    }),
    defineField({ name: "specifications", title: "Full Specifications", type: "text", rows: 15 }),
    defineField({
      name: "images",
      title: "Images",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
    }),
    defineField({
      name: "category",
      title: "Category",
      type: "string",
      options: {
        list: [
          "ACU / ASU / GPU",
          "Aircraft Heaters",
          "Ambulift",
          "Baggage Tractors",
          "Bagged Carts",
          "Belt Loaders",
          "Buses",
          "Cars",
          "Catering Trucks",
          "Chocks",
          "Container Transport",
          "Crash Tenders",
          "Deck Loaders / Cargo",
          "Deicing Units",
          "Dollies",
          "Forklifts",
          "Fuel Tankers",
          "Ground Support Equipment",
          "Loaders / Transporters",
          "Lorries",
          "Miscellaneous",
          "Other GSE",
          "Passenger Access",
          "PRM Units & Equipment",
          "Push Back Tractors",
          "Sweepers & Vacuum Tankers",
          "Toilet Units",
          "Towbar",
          "Tugs",
          "X-ray and Screening",
        ],
      },
    }),
    defineField({ name: "availableFrom", title: "Available From", type: "date" }),
    defineField({ name: "location", title: "Location", type: "string" }),
    defineField({ name: "serialNumber", title: "Serial Number", type: "string" }),
    defineField({ name: "featured", title: "Featured Listing", type: "boolean", initialValue: false }),
  ],
  orderings: [
    { title: "Newest First", name: "createdAtDesc", by: [{ field: "_createdAt", direction: "desc" }] },
    { title: "Sale Price Low–High", name: "priceAsc", by: [{ field: "salePrice.amount", direction: "asc" }] },
  ],
  preview: {
    select: { title: "title", subtitle: "category", media: "images.0.asset" },
  },
});
