import { defineType, defineField } from "sanity";

export const listing = defineType({
  name: "listing",
  title: "Equipment",
  type: "document",
  fields: [
    defineField({ name: "title", title: "Title", type: "string" }),
    defineField({ name: "slug", title: "Slug", type: "slug", options: { source: "title" } }),
    defineField({
      name: "published",
      title: "Published (visible on website)",
      type: "boolean",
      initialValue: true,
    }),
    defineField({
      name: "status",
      title: "Status",
      type: "array",
      of: [{ type: "string" }],
      options: {
        list: ["For Sale", "For Hire", "Sold"],
        layout: "grid",
      },
      initialValue: ["For Sale"],
    }),
    defineField({ name: "make", title: "Make / Manufacturer", type: "string" }),
    defineField({ name: "model", title: "Model", type: "string" }),
    defineField({ name: "year", title: "Year", type: "number" }),
    defineField({ name: "hours", title: "Operation Hours", type: "number" }),
    defineField({ name: "mileage", title: "Mileage (km)", type: "number" }),
    defineField({
      name: "fuelType",
      title: "Fuel Type",
      type: "string",
      options: { list: ["Diesel", "Petrol", "Electric", "Hybrid", "LPG", "Gas"], layout: "radio" },
    }),
    defineField({
      name: "transmission",
      title: "Transmission",
      type: "string",
      options: { list: ["Manual", "Automatic"], layout: "radio" },
    }),
    defineField({ name: "quantity", title: "Quantity Available", type: "string" }),
    defineField({
      name: "condition",
      title: "Condition",
      type: "string",
      options: { list: ["New", "Used – Excellent", "Used – Good", "Used – Fair"], layout: "radio" },
    }),
    defineField({
      name: "salePrice",
      title: "Sale Price",
      type: "object",
      fields: [
        defineField({ name: "amount", title: "Price (£)", type: "number" }),
        defineField({ name: "onApplication", title: "Price on Application", type: "boolean", initialValue: false }),
      ],
    }),
    defineField({
      name: "hirePrice",
      title: "Hire Price",
      type: "object",
      fields: [
        defineField({ name: "amount", title: "Price (£)", type: "number" }),
        defineField({ name: "onApplication", title: "Price on Application", type: "boolean", initialValue: false }),
        defineField({
          name: "period",
          title: "Per",
          type: "string",
          options: { list: ["Day", "Week", "Month", "Year"], layout: "radio" },
          initialValue: "Day",
        }),
      ],
    }),
    defineField({ name: "description", title: "Description", type: "text", rows: 5 }),
    defineField({
      name: "images",
      title: "Images",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
    }),
    defineField({
      name: "category",
      title: "Category",
      type: "string",
      options: {
        list: [
          "ACU / ASU / GPU",
          "Aircraft Heaters",
          "Ambulift",
          "Baggage Tractors",
          "Bagged Carts",
          "Belt Loaders",
          "Buses",
          "Cars",
          "Catering Trucks",
          "Chocks",
          "Container Transport",
          "Crash Tenders",
          "Deck Loaders / Cargo",
          "Deicing Units",
          "Dollies",
          "Forklifts",
          "Fuel Tankers",
          "Ground Support Equipment",
          "Loaders / Transporters",
          "Lorries",
          "Miscellaneous",
          "Other GSE",
          "Passenger Access",
          "PRM Units & Equipment",
          "Push Back Tractors",
          "Sweepers & Vacuum Tankers",
          "Toilet Units",
          "Towbar",
          "Tugs",
          "X-ray and Screening",
        ],
      },
    }),
    defineField({ name: "location", title: "Location", type: "string" }),
    defineField({ name: "serialNumber", title: "Serial Number", type: "string" }),
    defineField({ name: "featured", title: "Featured Listing", type: "boolean", initialValue: false }),
  ],
  orderings: [
    { title: "Newest First", name: "createdAtDesc", by: [{ field: "_createdAt", direction: "desc" }] },
    { title: "Sale Price Low–High", name: "priceAsc", by: [{ field: "salePrice.amount", direction: "asc" }] },
  ],
  preview: {
    select: { title: "title", subtitle: "status", media: "images.0" },
  },
});
